"""
apply_macro_nieuws.py -- past de MACRO-nieuws-wijziging toe op tekstbasis
(ongevoelig voor verschoven regelnummers). Draaien in /root/hbar_bot:
    python3 apply_macro_nieuws.py && rm apply_macro_nieuws.py
Elke vervanging moet precies één keer matchen; anders stopt het script
zonder iets te schrijven.
"""
import sys
EDITS = [
 [
  "llm_sentiment_engine.py",
  "Je bepaalt alleen WAT voor nieuws dit is, OVER WIE het gaat, of het NIEUW is en hoe GROOT het kan zijn.\nWees streng op nieuwheid: een kop die een bekend feit becommentarieert, samenvat of voorspelt is 'commentaar'.\nKoersanalyses, 'price prediction', 'is dit de bodem?', meningen van analisten = category 'marktcommentaar', novelty 'commentaar', magnitude 1.\nevent_key: korte canonieke naam van de onderliggende gebeurtenis in het Engels, zonder datum, zodat meerdere koppen over dezelfde gebeurtenis dezelfde key krijgen (bv. 'SEC decision HBAR ETF', 'Liquid sidechain pause', 'US CPI release').\"\"\"\n\nCLASSIFY_TOOL_SCHEMA = {\n",
  "Je bepaalt alleen WAT voor nieuws dit is, OVER WIE het gaat, of het NIEUW is en hoe GROOT het kan zijn.\nWees streng op nieuwheid: een kop die een bekend feit becommentarieert, samenvat of voorspelt is 'commentaar'.\nKoersanalyses, 'price prediction', 'is dit de bodem?', meningen van analisten = category 'marktcommentaar', novelty 'commentaar', magnitude 1.\nVoor algemeen nieuws (feed MACRO): entity 'macro'; category 'macro_fed' (Fed/rente/Treasury/inflatiecijfers), 'geopolitiek' (conflict, sancties, olie), 'handel_tarieven' of 'regulering_etf'. Alleen nieuws dat de financiële markten raakt krijgt magnitude >= 3; sport, entertainment en lokaal nieuws krijgen 1.\nevent_key: korte canonieke naam van de onderliggende gebeurtenis in het Engels, zonder datum, zodat meerdere koppen over dezelfde gebeurtenis dezelfde key krijgen (bv. 'SEC decision HBAR ETF', 'Liquid sidechain pause', 'US CPI release').\"\"\"\n\nCLASSIFY_TOOL_SCHEMA = {\n"
 ],
 [
  "llm_sentiment_engine.py",
  "            \"category\": {\"type\": \"string\", \"enum\": [\n                \"regulering_etf\", \"listing_exchange\", \"hack_security\", \"macro_fed\",\n                \"adoption_partnership\", \"tokenomics_unlock\", \"protocol_upgrade\",\n                \"marktcommentaar\", \"overig\"]},\n            \"entity\": {\"type\": \"string\", \"enum\": [\"BTC\", \"HBAR\", \"markt_breed\", \"andere_coin\"]},\n            \"novelty\": {\"type\": \"string\", \"enum\": [\"nieuw_feit\", \"update\", \"commentaar\"]},\n            \"magnitude_guess\": {\"type\": \"integer\", \"minimum\": 1, \"maximum\": 5,\n                                 \"description\": \"1 = irrelevant, 3 = kan de koers van deze asset merkbaar bewegen, 5 = marktschok (hack, verbod, ETF-besluit, Fed-verrassing)\"},\n",
  "            \"category\": {\"type\": \"string\", \"enum\": [\n                \"regulering_etf\", \"listing_exchange\", \"hack_security\", \"macro_fed\",\n                \"adoption_partnership\", \"tokenomics_unlock\", \"protocol_upgrade\",\n                \"geopolitiek\", \"handel_tarieven\", \"marktcommentaar\", \"overig\"]},\n            \"entity\": {\"type\": \"string\", \"enum\": [\"BTC\", \"HBAR\", \"markt_breed\", \"andere_coin\", \"macro\"]},\n            \"novelty\": {\"type\": \"string\", \"enum\": [\"nieuw_feit\", \"update\", \"commentaar\"]},\n            \"magnitude_guess\": {\"type\": \"integer\", \"minimum\": 1, \"maximum\": 5,\n                                 \"description\": \"1 = irrelevant, 3 = kan de koers van deze asset merkbaar bewegen, 5 = marktschok (hack, verbod, ETF-besluit, Fed-verrassing)\"},\n"
 ],
 [
  "regime_orchestrator.py",
  "from rss_news_client import RssNewsClient\nfrom rss_news_client import normalize_headline\n\nSENTIMENT_BIAS_BY_ASSET = {\n    \"BTC\": float(os.environ.get(\"SENTIMENT_BIAS_BTC\", \"0.17\")),\n    \"HBAR\": float(os.environ.get(\"SENTIMENT_BIAS_HBAR\", \"0.27\")),\n",
  "from rss_news_client import RssNewsClient\nfrom rss_news_client import normalize_headline\n\nMACRO_MIN_MAGNITUDE = int(os.environ.get(\"MACRO_MIN_MAGNITUDE\", \"3\"))   # alleen marktrelevant algemeen nieuws bewaren\nMACRO_MAX_PER_REFRESH = int(os.environ.get(\"MACRO_MAX_PER_REFRESH\", \"25\"))  # kostenrem op LLM-calls per verversing\n\nSENTIMENT_BIAS_BY_ASSET = {\n    \"BTC\": float(os.environ.get(\"SENTIMENT_BIAS_BTC\", \"0.17\")),\n    \"HBAR\": float(os.environ.get(\"SENTIMENT_BIAS_HBAR\", \"0.27\")),\n"
 ],
 [
  "regime_orchestrator.py",
  "                    f\"HANDMATIGE CONTROLE DRINGEND VEREIST.\",\n                )\n\n    async def _refresh_sentiment_if_due(self):\n        if (time.time() - self._last_sentiment_refresh) < SENTIMENT_REFRESH_SECONDS:\n            return\n\n        for asset in (\"BTC\", \"HBAR\"):\n            items = self.rss_news.fetch_news(asset, max_age_hours=4.0)\n            # Messari's News API uitgeschakeld (27 aug 2026) -- vereist een\n",
  "                    f\"HANDMATIGE CONTROLE DRINGEND VEREIST.\",\n                )\n\n    async def _verwerk_macro_nieuws(self):\n        items = self.rss_news.fetch_news(\"MACRO\", max_age_hours=4.0)\n        nieuw = [i for i in items if i.id not in self._processed_news_ids]\n        if not nieuw:\n            return\n        try:\n            bekend = {normalize_headline(h) for h in await self.db.recent_headlines(24.0)}\n        except Exception:\n            bekend = set()\n        try:\n            async with self.db._pool.acquire() as conn:\n                rows = await conn.fetch(\"SELECT headline_key FROM news_events WHERE created_at > now() - interval '48 hours'\")\n            bekend |= {r[\"headline_key\"] for r in rows}\n        except Exception:\n            pass\n        gezien, bewaard, gezien_n = set(), 0, 0\n        for i in nieuw:\n            self._processed_news_ids.add(i.id)\n            sleutel = normalize_headline(i.title)\n            if not sleutel or sleutel in bekend or sleutel in gezien:\n                continue\n            gezien.add(sleutel)\n            gezien_n += 1\n            if gezien_n > MACRO_MAX_PER_REFRESH:\n                break\n            cls = self.llm.classify_headline(\"MACRO\", i.title)\n            if cls is None or cls.magnitude_guess < MACRO_MIN_MAGNITUDE:\n                continue\n            await self.db.log_news_event(\n                asset=\"MACRO\", headline=i.title, headline_key=sleutel, published_at=i.published_at,\n                source_feed=i.source_feed, url=i.url, category=cls.category, entity=cls.entity,\n                novelty=cls.novelty, magnitude_guess=cls.magnitude_guess, event_key=cls.event_key,\n                rationale=cls.rationale,\n            )\n            bewaard += 1\n            print(f\"[nieuws] MACRO: {cls.category}/{cls.novelty} m={cls.magnitude_guess} [{cls.event_key}] {i.title[:60]}\")\n        if gezien_n:\n            print(f\"[nieuws] MACRO: {gezien_n} nieuwe koppen beoordeeld, {bewaard} relevant bewaard.\")\n\n    async def _refresh_sentiment_if_due(self):\n        if (time.time() - self._last_sentiment_refresh) < SENTIMENT_REFRESH_SECONDS:\n            return\n\n        # ALGEMEEN NIEUWS (10 sep 2026): aparte tak -- alleen classificeren\n        # en bewaren (news_events), geen richtingsscore, geen invloed op de\n        # regime-beslissing. Alleen koppen met omvang >= MACRO_MIN_MAGNITUDE\n        # worden opgeslagen; de rest is voor de markt niet relevant.\n        try:\n            await self._verwerk_macro_nieuws()\n        except Exception as e:\n            print(f\"[nieuws] MACRO-tak mislukt (niet kritiek): {e}\")\n\n        for asset in (\"BTC\", \"HBAR\"):\n            items = self.rss_news.fetch_news(asset, max_age_hours=4.0)\n            # Messari's News API uitgeschakeld (27 aug 2026) -- vereist een\n"
 ],
 [
  "rss_news_client.py",
  "        # van de exacte tag-URL-structuur van een specifieke nieuwssite.\n        \"https://news.google.com/rss/search?q=hedera+hbar+when:7d&hl=en-US&gl=US&ceid=US:en\",\n    ],\n}\n\n# Simpele keyword-filter voor de bredere feeds, om te voorkomen dat elk\n",
  "        # van de exacte tag-URL-structuur van een specifieke nieuwssite.\n        \"https://news.google.com/rss/search?q=hedera+hbar+when:7d&hl=en-US&gl=US&ceid=US:en\",\n    ],\n    # ALGEMEEN/MACRO-NIEUWS (10 sep 2026, op verzoek): Fed, Treasury\n    # (Bessent), tarieven, geopolitiek (Iran, sancties, olie), recessie.\n    # Voedt ALLEEN news_events (classificatie + event-study), geen\n    # richtingsscore -- het gaat over de hele markt, niet over HBAR.\n    # Alle bronnen keyloos. Google-News-query's zijn bewust smal: algemeen\n    # nieuws is honderden koppen per dag, alleen het marktrelevante deel\n    # mag door.\n    \"MACRO\": [\n        \"https://feeds.apnews.com/rss/apf-business\",\n        \"https://feeds.apnews.com/rss/apf-topnews\",\n        \"https://www.cnbc.com/id/10000664/device/rss/rss.html\",   # CNBC Economy\n        \"https://www.cnbc.com/id/100003114/device/rss/rss.html\",  # CNBC Top News\n        \"https://feeds.bbci.co.uk/news/business/rss.xml\",\n        \"https://news.google.com/rss/search?q=(Federal+Reserve+OR+Powell+OR+FOMC)+when:1d&hl=en-US&gl=US&ceid=US:en\",\n        \"https://news.google.com/rss/search?q=(Bessent+OR+Treasury+Secretary)+when:1d&hl=en-US&gl=US&ceid=US:en\",\n        \"https://news.google.com/rss/search?q=(tariffs+OR+trade+war)+markets+when:1d&hl=en-US&gl=US&ceid=US:en\",\n        \"https://news.google.com/rss/search?q=(Iran+OR+Israel+OR+Russia+OR+Taiwan)+(strike+OR+attack+OR+sanctions+OR+war)+when:1d&hl=en-US&gl=US&ceid=US:en\",\n        \"https://news.google.com/rss/search?q=(oil+prices+OR+recession+OR+inflation+data)+when:1d&hl=en-US&gl=US&ceid=US:en\",\n    ],\n}\n\n# Simpele keyword-filter voor de bredere feeds, om te voorkomen dat elk\n"
 ],
 [
  "rss_news_client.py",
  "ASSET_KEYWORDS = {\n    \"BTC\": [\"bitcoin\", \"btc\"],\n    \"HBAR\": [\"hedera\", \"hbar\", \"hashgraph\"],\n}\n\n# Automatisch gegenereerde valuta-omreken-pagina's (bv. van Bybit) bevatten\n",
  "ASSET_KEYWORDS = {\n    \"BTC\": [\"bitcoin\", \"btc\"],\n    \"HBAR\": [\"hedera\", \"hbar\", \"hashgraph\"],\n    # MACRO: trefwoordpoort -- zonder minstens één van deze woorden is een\n    # algemene kop (sport, entertainment, lokaal) niet marktrelevant.\n    \"MACRO\": [\"fed \", \"federal reserve\", \"powell\", \"fomc\", \"rate cut\", \"rate hike\", \"interest rate\",\n              \"bessent\", \"treasury\", \"tariff\", \"trade war\", \"sanction\", \"iran\", \"israel\", \"russia\",\n              \"ukraine\", \"taiwan\", \"china\", \" oil \", \"crude\", \"opec\", \"inflation\", \"cpi\", \"jobs report\",\n              \"payrolls\", \"recession\", \"gdp\", \"stock market\", \"wall street\", \"s&p\", \"nasdaq\",\n              \"dollar\", \" bond\", \"yield\", \"debt ceiling\", \"shutdown\", \"trump\", \"white house\",\n              \"sec \", \"regulat\", \"crypto\", \"bitcoin\", \"stablecoin\"],\n}\n\n# Automatisch gegenereerde valuta-omreken-pagina's (bv. van Bybit) bevatten\n"
 ]
]

def main():
    inhoud = {}
    for bestand, oud, nieuw in EDITS:
        s = inhoud.get(bestand) or open(bestand, encoding="utf-8").read()
        n = s.count(oud)
        if n != 1:
            print(f"STOP: {bestand}: fragment {n}x gevonden (verwacht 1). Niets geschreven.")
            print("--- fragment ---"); print(oud[:400]); sys.exit(1)
        inhoud[bestand] = s.replace(oud, nieuw, 1)
    for bestand, s in inhoud.items():
        open(bestand, "w", encoding="utf-8").write(s)
        print(f"OK: {bestand}")

if __name__ == "__main__":
    main()
